# Generated by Django 4.2.13 on 2024-07-08 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('power_current', models.FloatField()),
            ],
        ),
    ]
